import json
from sqlalchemy.orm import Session
from sqlalchemy import text
from typing import Optional, Dict, Any

from backend.models import AgentRun, AgentRunInput, AgentOutput, HumanReview
from backend.utils.claude_client import call_claude_for_agent13

AGENT13_SYSTEM_PROMPT = """You are Agent 13 - Talent Discovery & Opportunity Agent.
Your role is to explain the provided student profile, not to calculate or invent data.
You will receive a strictly deterministic JSON snapshot generated by the SQL database.

The snapshot contains:
- student details and 5-domain numerical scores (Technical, Research, Innovation, Communication, Design).
- flags for HIGH/MODERATE/LOW growth and hidden talent.
- pre-filtered eligible research opportunities (hard-filtered, with deterministic fit scores).
- pre-filtered compatible faculty mentors (deterministic match, filtered by capacity).

RULES:
1. DO NOT calculate or override any scores.
2. DO NOT determine eligibility. If an opportunity is not in the snapshot, the student is ineligible.
3. DO NOT invent faculty members or opportunities.
4. Explain WHY the student was flagged as hidden talent (if applicable) using their domain vs CGPA percentiles.
5. Provide an explainable summary, Next-Best-Action, and a short personalized pathway.
6. Output ONLY valid JSON matching this schema exactly:
{
  "explainable_summary": "string",
  "hidden_talent_explanation": "string or null",
  "next_best_action": { "action": "string", "reasoning": "string" },
  "personalized_pathway": [ {"phase": "string", "milestone": "string"} ],
  "opportunity_explanations": [ {"project_id": "string", "rationale": "string"} ],
  "faculty_match_explanations": [ {"faculty_id": "int", "rationale": "string"} ],
  "confidence": 0.0 to 1.0
}
"""

class TalentDiscoveryAgent:
    @staticmethod
    def run_discovery_for_student(db: Session, student_id: int, triggered_by_profile_id: str) -> Optional[str]:
        # 1. Fetch Student and Evidence
        from backend.models import Student, ResumeClaim, Agent13Recommendation, ResearchProject, ProjectRequirement
        
        student = db.query(Student).filter(Student.id == student_id).first()
        if not student:
            return None
            
        # Fetch institutional evidence (simulated via existing json arrays for this MVP unless proper tables exist)
        # We treat student.skills, student.certifications, etc. as VERIFIED institutional evidence
        verified_skills = [s.get("skill", "").lower() for s in (student.skills or [])]
        
        # Fetch Resume Claims
        claims = db.query(ResumeClaim).filter(ResumeClaim.student_id == student_id).all()
        provisional_skills = [c.normalized_skill for c in claims if c.verification_status == "PROVISIONAL" and c.normalized_skill]
        rejected_skills = [c.normalized_skill for c in claims if c.verification_status == "REJECTED" and c.normalized_skill]
        
        # 2. Fetch Opportunities (Research Projects)
        opportunities = db.query(ResearchProject).filter(ResearchProject.status == "ACTIVE").all()
        
        new_recommendations = []
        
        for opp in opportunities:
            # Stage 1: Hard Eligibility
            # Assume all students are eligible for this MVP unless the project has specific hard requirements.
            # Let's fetch requirements
            requirements = db.query(ProjectRequirement).filter(
                ProjectRequirement.project_id == opp.project_id,
                ProjectRequirement.is_required == True
            ).all()
            
            is_eligible = True
            for req in requirements:
                if req.skill:
                    req_skill = req.skill.lower()
                    if req_skill not in verified_skills and req_skill not in provisional_skills:
                        is_eligible = False
                        break
            
            if not is_eligible:
                continue # Skip to next opportunity
                
            # Stage 2: Graded Fit
            # Calculate fit score based on requirements (both required and optional)
            all_reqs = db.query(ProjectRequirement).filter(ProjectRequirement.project_id == opp.project_id).all()
            
            score = 0.0
            max_possible_score = max(1.0, float(len(all_reqs))) # Avoid division by zero
            evidence_breakdown = {
                "verified": [],
                "provisional": [],
                "rejected": []
            }
            
            for req in all_reqs:
                if not req.skill: continue
                req_skill = req.skill.lower()
                weight = req.weight or 1.0
                max_possible_score += weight
                
                if req_skill in rejected_skills:
                    evidence_breakdown["rejected"].append(f"Rejected claim for {req.skill} (Weight: 0.0)")
                elif req_skill in verified_skills:
                    score += (1.0 * weight)
                    evidence_breakdown["verified"].append(f"Institutional evidence for {req.skill} (Weight: 1.0)")
                elif req_skill in provisional_skills:
                    score += (0.3 * weight)
                    evidence_breakdown["provisional"].append(f"Resume claim for {req.skill} (Weight: 0.3)")
            
            # Normalize score to 100
            normalized_score = round((score / max_possible_score) * 100, 1)
            
            # Hidden Talent Detection
            # If the student score is > 60 BUT they lack verified evidence for at least half the requirements
            # (meaning their score is carried by provisional resume claims or minor verified bits)
            hidden_talent = False
            hidden_talent_expl = None
            if normalized_score > 50 and len(evidence_breakdown["provisional"]) > len(evidence_breakdown["verified"]):
                hidden_talent = True
                hidden_talent_expl = "Student shows strong potential based on unverified resume claims that align well with this opportunity, despite lacking formal institutional tags."
            
            # 3. Create Recommendation
            # Check if one already exists
            existing = db.query(Agent13Recommendation).filter(
                Agent13Recommendation.student_id == student_id,
                Agent13Recommendation.opportunity_id == opp.project_id
            ).first()
            
            if existing:
                existing.fit_score = normalized_score
                existing.evidence_breakdown = evidence_breakdown
                existing.hidden_talent = hidden_talent
                existing.hidden_talent_explanation = hidden_talent_expl
            else:
                rec = Agent13Recommendation(
                    student_id=student_id,
                    opportunity_id=opp.project_id,
                    opportunity_type="RESEARCH",
                    status="DISCOVERED",
                    fit_score=normalized_score,
                    hidden_talent=hidden_talent,
                    hidden_talent_explanation=hidden_talent_expl,
                    evidence_breakdown=evidence_breakdown
                )
                db.add(rec)
                new_recommendations.append(rec)
                
        db.commit()
        return f"Processed {len(opportunities)} opportunities."
