import json
from sqlalchemy.orm import Session
from sqlalchemy import text
from typing import Optional, Dict, Any

from backend.models import AgentRun, AgentRunInput, AgentOutput, HumanReview
from backend.utils.claude_client import call_claude_for_agent13

AGENT13_SYSTEM_PROMPT = """You are Agent 13 - Talent Discovery & Opportunity Agent.
Your role is to explain the provided student profile, not to calculate or invent data.
You will receive a strictly deterministic JSON snapshot generated by the SQL database.

The snapshot contains:
- student details and 5-domain numerical scores (Technical, Research, Innovation, Communication, Design).
- flags for HIGH/MODERATE/LOW growth and hidden talent.
- pre-filtered eligible research opportunities (hard-filtered, with deterministic fit scores).
- pre-filtered compatible faculty mentors (deterministic match, filtered by capacity).

RULES:
1. DO NOT calculate or override any scores.
2. DO NOT determine eligibility. If an opportunity is not in the snapshot, the student is ineligible.
3. DO NOT invent faculty members or opportunities.
4. Explain WHY the student was flagged as hidden talent (if applicable) using their domain vs CGPA percentiles.
5. Provide an explainable summary, Next-Best-Action, and a short personalized pathway.
6. Output ONLY valid JSON matching this schema exactly:
{
  "explainable_summary": "string",
  "hidden_talent_explanation": "string or null",
  "next_best_action": { "action": "string", "reasoning": "string" },
  "personalized_pathway": [ {"phase": "string", "milestone": "string"} ],
  "opportunity_explanations": [ {"project_id": "string", "rationale": "string"} ],
  "faculty_match_explanations": [ {"faculty_id": "int", "rationale": "string"} ],
  "confidence": 0.0 to 1.0
}
"""

class TalentDiscoveryAgent:
    @staticmethod
    def run_discovery_for_student(db: Session, student_id: int, triggered_by_profile_id: str) -> Optional[str]:
        """
        Executes Agent 13 for a specific student.
        1. Creates AgentRun.
        2. Queries the 3 deterministic SQL views to build the JSON snapshot.
        3. Saves AgentRunInput.
        4. Calls Claude with the snapshot.
        5. Saves AgentOutput and HumanReview.
        Returns the output_id if successful, None otherwise.
        """
        # 1. Create Run
        run = AgentRun(agent_code="A13_FAST_LEARNER", triggered_by=triggered_by_profile_id, status="STARTED")
        db.add(run)
        db.commit()
        db.refresh(run)

        # 2. Query Deterministic SQL Views
        strength_rows = db.execute(
            text("SELECT * FROM outcomes.v_student_strength_profile WHERE student_id = :sid"),
            {"sid": student_id}
        ).fetchall()

        if not strength_rows:
            run.status = "FAILED - STUDENT NOT FOUND"
            db.commit()
            return None

        eligibility_fit = db.execute(
            text("SELECT * FROM outcomes.v_opportunity_eligibility_and_fit WHERE student_id = :sid AND is_eligible = TRUE"),
            {"sid": student_id}
        ).fetchall()

        faculty_matches = db.execute(
            text("SELECT * FROM outcomes.v_faculty_mentor_compatibility WHERE student_id = :sid"),
            {"sid": student_id}
        ).fetchall()

        first = strength_rows[0]

        # Build Context Snapshot
        context_snapshot = {
            "student": {
                "id": first.student_id,
                "branch": first.branch,
                "cgpa": float(first.cgpa) if first.cgpa else None,
                "cgpa_percentile": float(first.cgpa_percentile) if first.cgpa_percentile else None
            },
            "scores": {
                row.domain: float(row.domain_score) for row in strength_rows
            },
            "flags": {
                "is_hidden_talent": any(row.is_hidden_talent for row in strength_rows),
                "hidden_talent_domains": [row.domain for row in strength_rows if row.is_hidden_talent],
                "growth_status": first.growth_status
            },
            "eligible_opportunities": [
                {
                    "project_id": str(row.project_id),
                    "fit_score": float(row.fit_score) if row.fit_score else 0.0
                } for row in eligibility_fit
            ],
            "compatible_faculty": [
                {
                    "faculty_id": row.faculty_id,
                    "faculty_name": row.faculty_name,
                    "compatibility_score": float(row.compatibility_score) if row.compatibility_score else 0.0
                } for row in faculty_matches
            ]
        }

        # 3. Save Input Snapshot
        run_input = AgentRunInput(run_id=run.run_id, context_snapshot=context_snapshot)
        db.add(run_input)
        db.commit()

        # 4. Call Claude
        claude_response = call_claude_for_agent13(
            system_prompt=AGENT13_SYSTEM_PROMPT,
            context_snapshot=context_snapshot
        )

        if not claude_response:
            run.status = "FAILED - LLM ERROR"
            db.commit()
            return None

        # 5. Save Output and Review
        output = AgentOutput(
            run_id=run.run_id,
            subject_type="STUDENT",
            subject_id=student_id,
            payload=claude_response,
            reasoning_summary=claude_response.get("explainable_summary", "No summary provided."),
            confidence=float(claude_response.get("confidence", 0.0))
        )
        db.add(output)
        db.commit()
        db.refresh(output)

        review = HumanReview(
            output_id=output.output_id,
            decision="PENDING"
        )
        db.add(review)
        
        run.status = "COMPLETED"
        db.commit()

        return output.output_id
